server:
  port: 8889
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seen2016/SpringCloundTest
          search-paths: config
          username: seen2016
          passphrase: lpf881220.
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/